# simulation/legal_limits.py
LEGAL_LIMITS = {
    "EU_Urban_Wastewater": {
        "nitrate_ppm": 10,
        "phosphate_ugL": 10,
        "temperature_c": 25,
        "ph_min": 6.5,
        "ph_max": 8.5,
        "dissolved_oxygen_mgL": 6.0,
        "turbidity_ntu": 25,
        "bod_mgL": 25,
        "cod_mgL": 125,
        "lead_ugL": 1.0,
        "mercury_ugL": 0.5,
    },
    "India_CPCB": {
        "nitrate_ppm": 10,
        "phosphate_ugL": 5,
        "temperature_c": 27,
        "ph_min": 6.0,
        "ph_max": 9.0,
        "dissolved_oxygen_mgL": 4.0,
        "turbidity_ntu": 30,
        "bod_mgL": 30,
        "cod_mgL": 250,
        "lead_ugL": 0.1,
        "mercury_ugL": 0.01,
    },
    "US_EPA_CWA": {
        "nitrate_ppm": 10,
        "phosphate_ugL": 8,
        "temperature_c": 26,
        "ph_min": 6.5,
        "ph_max": 8.5,
        "dissolved_oxygen_mgL": 5.0,
        "turbidity_ntu": 50,
        "bod_mgL": 30,
        "cod_mgL": 120,
        "lead_ugL": 0.05,
        "mercury_ugL": 0.002,
    },
    "Custom_Strict": {
        "nitrate_ppm": 5,
        "phosphate_ugL": 2,
        "temperature_c": 23,
        "ph_min": 6.8,
        "ph_max": 8.2,
        "dissolved_oxygen_mgL": 7.0,
        "turbidity_ntu": 10,
        "bod_mgL": 10,
        "cod_mgL": 50,
        "lead_ugL": 0.01,
        "mercury_ugL": 0.001,
    }
}
